{
 "title": "API Server results comparison",
 "time": { "from": "2024-10-29T11:45:00.000Z", "to": "2024-10-29T14:45:00.000Z" },
 "templating": {
  "list": [
   { "name": "offset", "label": "Offset", "query": "0m" },
   { "name": "prowjob_base", "label": "Prowjob Baseline", "query": { "query": "label_values(up,prowjob)" } },
   { "name": "prowjob_tested", "label": "Prowjob Tested", "query": { "query": "label_values(up,prowjob)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "apiserver_request_total diff",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg by (verb) (sum by(resource, verb) \n(irate(apiserver_request_total{job=\"apiserver\", prowjob=\"$prowjob_tested\", code=\"200\"}[5m] offset $offset)) - sum by(resource, verb) \n(irate(apiserver_request_total{job=\"apiserver\", prowjob=\"$prowjob_base\", code=\"200\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GET/LIST request diff",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\",prowjob=\"$prowjob_tested\"}[5m] offset $offset))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\",prowjob=\"$prowjob_tested\"}[5m] offset $offset)) - sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\",prowjob=\"$prowjob_base\"}[5m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\",prowjob=\"$prowjob_base\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write request diff",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\",prowjob=\"$prowjob_tested\"}[5m] offset $offset))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\",prowjob=\"$prowjob_tested\"}[5m] offset $offset)) - sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\",prowjob=\"$prowjob_base\"}[5m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\",prowjob=\"$prowjob_base\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Kube API Server CPU usage diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"apiserver\", prowjob=\"$prowjob_tested\"}[5m] offset $offset)) - sum(irate(process_cpu_seconds_total{job=\"apiserver\", prowjob=\"$prowjob_base\"}[5m] offset $offset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube Scheduler CPU Usage diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"scheduler\", prowjob=\"$prowjob_tested\"}[5m] offset $offset)) - sum(irate(process_cpu_seconds_total{job=\"scheduler\", prowjob=\"$prowjob_base\"}[5m] offset $offset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube Controller Manager CPU usage diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"kube-controller-manager\", prowjob=\"$prowjob_tested\"}[1m] offset $offset)) - sum(irate(process_cpu_seconds_total{job=\"kube-controller-manager\", prowjob=\"$prowjob_base\"}[1m] offset $offset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etcd CPU Usage diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"etcd\", prowjob=\"$prowjob_tested\"}[5m] offset $offset)) - sum(irate(process_cpu_seconds_total{job=\"etcd\", prowjob=\"$prowjob_base\"}[5m] offset $offset))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "openshift:memory_usage_bytes ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "openshift:memory_usage_bytes:sum{prowjob=\"$prowjob_base\"} offset $offset",
     "legendFormat": "__auto"
    },
    {
     "expr": "openshift:memory_usage_bytes:sum{prowjob=\"$prowjob_tested\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-apiserver memory usage diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{prowjob=\"$prowjob_base\", namespace=\"openshift-kube-apiserver\"}) offset $offset - sum(container_memory_usage_bytes{prowjob=\"$prowjob_tested\", namespace=\"openshift-kube-apiserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-controller-manager memory usage diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{prowjob=\"$prowjob_base\", namespace=\"openshift-kube-controller-manager\"}) offset $offset - sum(container_memory_usage_bytes{prowjob=\"$prowjob_tested\", namespace=\"openshift-controller-manager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-scheduler memory usage diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{prowjob=\"$prowjob_base\", namespace=\"openshift-kube-scheduler\"}) offset $offset - sum(container_memory_usage_bytes{prowjob=\"$prowjob_tested\", namespace=\"openshift-kube-scheduler\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd memory usage diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{prowjob=\"$prowjob_base\", namespace=\"openshift-etcd\"}) offset $offset - sum(container_memory_usage_bytes{prowjob=\"$prowjob_tested\", namespace=\"openshift-etcd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Request processing time diff",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rest_client_request_duration_seconds_bucket{prowjob=\"$prowjob_tested\"}[1m])) by (le)) - histogram_quantile(0.95, sum(rate(rest_client_request_duration_seconds_bucket{prowjob=\"$prowjob_base\"}[1m] offset $offset)) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response size diff",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_response_sizes_bucket{prowjob=\"$prowjob_tested\"}[1m] offset $offset)) by (le)) - histogram_quantile(0.95, sum(rate(apiserver_response_sizes_bucket{prowjob=\"$prowjob_base\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}